# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "SITIBA 2016"
email: "luciocouto@hotmail.com"
description: "SITIBA Simpósio de Terapia Intensiva do Interior da Bahia"
baseurl: "/zeppelin"
url: "https://safe.edu.br"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: ""
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "SITIBA"
organizerAlternateName: "Simpósio de Terapia Intensiva do Interior da Bahia"
organizerDescription: "Evento de caráter científico que firma o posicionamento de Feira de Santana como centro emergente no cuidado ao paciente crítico, contando com a participação da equipe multiprofissional. Espera-se a participação de 200 profissionais dentre médicos, enfermeiros, fisioterapeutas, odontólogos e nutricionistas, além de nomes conceituados na especialidade nesse importante momento para a terapia intensiva da Bahia."
organizerEmail: "luciocouto@hotmail.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://lviv.gdg.org.ua/"

# Head
metaKeywords: "evento, saúde, uti, palestra, bahia, sitiba, feira de santana, terapia, intensiva"
twitterAccount: "@Sitiba"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
# c4pUrl: "https://bit.ly/dfua-c4p"
# c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 # - {permalink: "/", text: "Home"}
 # - {permalink: "/blog/", text: "Blog"}
 # - {permalink: "/schedule/", text: "Schedule"}
 # - {permalink: "/speakers/", text: "Speakers"}
 # - {permalink: "/team/", text: "Team"}
 # - {permalink: "/logistics/", text: "Logistics"}
 # - {permalink: "/hackathon/", text: "Hackathon"}
# bottomNavigationLinks:
#  - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
# rightNavigationButtons:
#  - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}

# Hero Block
heroImage: "dna.jpg"
heroTitle: "SITIBA <typeout> 2016"
eventDate: "Setembro de 2016"
typeoutTextValues: '"", "Feira de Santana"'
typeoutFallback: "Season"
heroButtons:
 #- {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
 - {permalink: "/#tickets", text: "Comprar Ingresso"}

# About Block
aboutTitle: "Sobre o evento"
aboutBlock:
 - {title: "Palestrantes", image: "551.png", text: "Grandes nomes da área de Segurança e Qualidade em Terapia Intensiva reunidos no mesmo lugar." }
 - {title: "Mesa Redonda", image: "workshop.jpg", text: "Com o tema: O paciente cirúrgico na UTI. Serão abordados os aspectos do paciente cirúrgico crítico, manejo peri e pós operatório, pós operatório de cirurgia cardíaca,
e sindrome compartimental abdominal" }
 - {title: "Curso", image: "courtse.jpg", text: "Via aérea básica e avançada das 8:00 às 12:00.
 Público alvo – (Médicos), vagas limitadas para no máximo de 20 alunos" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "200", specialCharacter: "+", info: "inscritos", detail: "de todas as partes do estado"}
 - {count: "12", specialCharacter: "+", info: "horas", detail: "de puro conhecimento"}
 - {count: "4", specialCharacter: "+", info: "palestrantes", detail: "de renome nacional"}


# Latest News Block
#latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Palestrantes"
rockstarSpeakersButtonText: "Veja todos os palestrantes"

# Location Block
locationBlockTitle: "Localização"
eventLocationName: "Edifício Atmosfera"
eventLocationLink: "https://www.google.com.br/maps/place/Nossa+Casa/@-12.2600251,-38.9442666,18z/data=!4m8!1m2!2m1!1sedificio+atmosfera+feira+de+santana!3m4!1s0x7143791f9a74d15:0x97d6f3e5eb2965f6!8m2!3d-12.260017!4d-38.944243?hl=pt-BR"
eventStreetAddress: "R. São Domingos, 588 "
eventAddressLocality: "Santa Monica"
eventAddressLocalityRegion: "Feira de Santana"
eventPostalCode: "44077-465"
eventAddressCountry: "Brasil"
eventStartTime: "2016-09-16T10:00"
eventDoorTime: "09:00"
eventEndTime: "2016-09-17T18:00"
eventPlaceCoordinates: "-12.2600251, -38.9442666"
mapCenterCoordinates: "-12.2600251, -38.9442674"
mapMobileCenterCoordinates: "-12.2600251, -38.9442674"

# Venue Block
venueBlockTitle: "Local"
venueBigImage: "atmosfera.jpg"
venueSmallImage1: "atmosfera2.jpg"
venueSmallImage2: "atmosfera3.jpg"
venueSmallImage3: "igreja.jpg"
venueTitle: "Edifício Atmosfera"
venueFeatures: ["- Localizado na São Domingos", " - Em frente ao restaurante Bherman"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "devfest"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Apoio"
partnersTitle: "Parceiros"
#partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
# subscribeImage: "subscribe.jpg"
# subscribeTitle: "Receba nossa newslatter"
# subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
# subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Ingressos"
ticketsInfo: "Aproveite e garanta logo o seu ingresso no 1º Lote."
ticketsOffers:
 -
  name: "1º Lote (Médicos Associados)"
  price: "180"
  priceCurrency: "R$"
  ticketsNumber: "150"
  #ribbon: "-20%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Comprar"
  ticketContentList: ["Este valor permanecerá até o dia 16/08"]
  validFrom: "2016-07-28T10:00"
  validThrough: "2016-08-16T23:59"
 -
  name: "2º Lote (Médicos Associados)"
  price: "200"
  priceCurrency: "R$"
  ticketsNumber: "150"
  #ribbon: "-20%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Comprar"
  ticketContentList: ["Este valor permanecerá até o dia 15/09"]
  validFrom: "2016-08-17T10:00"
  validThrough: "2016-09-15T23:59"
 -
  name: "3º Lote (Médicos Associados)"
  price: "220"
  priceCurrency: "R$"
  ticketsNumber: "20"
 # ribbon: "-20%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Comprar"
  ticketContentList: ["Este é valor no dia do evento 16/09"]
  validFrom: "2016-09-16T00:00"
  validThrough: "2016-09-16T23:59"
  soldOut: true
  soldOutText: "Inscrição no local"
 -
  name: "1º Lote (Médicos)"
  price: "180"
  priceCurrency: "R$"
  ticketsNumber: "200"
  #ribbon: "-20%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Comprar"
  ticketContentList: ["Este valor permanecerá até o dia 16/08"]
  validFrom: "2016-07-28T10:00"
  validThrough: "2016-08-16T23:59"
 -
  name: "2º Lote (Médicos)"
  price: "220"
  priceCurrency: "R$"
  ticketsNumber: "150"
  #ribbon: "-20%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Comprar"
  ticketContentList: ["Este valor permanecerá até o dia 15/09"]
  validFrom: "2016-08-17T10:00"
  validThrough: "2016-09-15T23:59"
 -
  name: "3º Lote (Médicos)"
  price: "240"
  priceCurrency: "R$"
  ticketsNumber: "20"
  #ribbon: "-20%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Comprar"
  ticketContentList: ["Este é valor no dia do evento 16/09"]
  validFrom: "2016-09-16T00:00"
  validThrough: "2016-09-16T23:59"
  soldOut: true
  soldOutText: "Inscrição no local"
 -
  name: "1º Lote (Estudante)"
  price: "80"
  priceCurrency: "R$"
  ticketsNumber: "200"
  #ribbon: "-20%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Comprar"
  ticketContentList: ["Este valor permanecerá até o dia 16/08"]
  validFrom: "2016-07-28T10:00"
  validThrough: "2016-08-16T23:59"
 -
  name: "2º Lote (Estudante)"
  price: "220"
  priceCurrency: "R$"
  ticketsNumber: "150"
  #ribbon: "-20%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Comprar"
  ticketContentList: ["Este valor permanecerá até o dia 15/09"]
  validFrom: "2016-08-17T10:00"
  validThrough: "2016-09-15T23:59"
 -
  name: "3º Lote (Estudante)"
  price: "240"
  priceCurrency: "R$"
  ticketsNumber: "20"
  #ribbon: "-20%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Comprar"
  additionalInfo: "Será exigido o comprovante de matrícula no check-in."
  ticketContentList: ["Este é valor no dia do evento 16/09"]
  validFrom: "2016-09-16T00:00"
  validThrough: "2016-09-16T23:59"
  soldOut: true
  soldOutText: "Inscrição no local"

# Footer
# socialLinks:
#  - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
#  - {link: "https://twitter.com/intent/user?screen_name=GDGLviv", icon: "twitter"}
#  - {link: "https://facebook.com/GDGLviv", icon: "facebook"}
#  - {permalink: "/feed.xml", icon: "rss"}
# footerBlocks:
#  -
#   title: "Links"
#   links:
#    - {link: "http://gdg.org.ua", text: "GDG.org.ua"}
#    - {link: "https://developers.google.com", text: "Google Developers"}
#  -
#   title: "Contacts"
#   links:
#    - {link: "mailto:lviv@gdg.org.ua", text: "lviv@gdg.org.ua"}
#  -
#   title: "FAQ"
#   links:
#    - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
# blogTitle: "Latest news"
# blogCommentsEnabled: true
# discusShortName: "devfestua"

# # Speakers List Block
# showSessions: true

# # Team Block
# teamBlockTitle: "About us"
# aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# # Logistics Find Way Block
# findWayTitle: "Find your way here"
# findWayDistance: "Distance"
# findWayDriving: "DRIVING"
# findWayWalking: "WALKING"
# findWayBicycling: "BICYCLING"
# findWayTransit: "TRANSIT"
# findWayFindFlight: "Find Flight"
# logisticsMapCenterCoordinates: "49.056728, 3.117289"
# logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
# logisticsMapAutoDirections: false

# # Logistics Direction Details Block
# directionDetailsImage: "direction-details.jpg"
# directionDetailsTitle: "Get around Lviv"
# directionDetailsCards:
#  - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
#  - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
#  - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
# directionDetailsWideCards:
#  -
#   title: "Questions?"
#   subCards:
#    -
#     title: "Hotels"
#     links:
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#    -
#     title: "Registration"
#     links:
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#    -
#     title: "Attendance Details"
#     links:
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# # Hackathon
# hackathonTitle: "Hackathon"
# enableHackathon: true

# # Hackathon About Block
# aboutHackathonTitle: "Meet our themes"
# hackathonRows:
#  - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
#  - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
#  - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# # Hackathon Judges Block
# judgesImage: "judges.jpg"
# judgesTitle: "Judges"

# # Hackathon Prizes Block
# prizesTitle: "Prizes"
# prizes:
#  - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
#  - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
#  - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# # Hackathon Location Block
# hackathonLocationBlockTitle: "Location"
# hackathonLocationName: "Communa"
# hackathonLocationLink: "http://communa.net.ua/"
# hackathonStreetAddress: "1 Halytska St"
# hackathonAddressLocality: "Lviv"
# hackathonAddressLocalityRegion: "Lvivska"
# hackathonPostalCode: "79000"
# hackathonAddressCountry: "Ukraine"
# hackathonTimeTitle: "Hack through"
# hackathonStartTime: "2014-10-24T10:00"
# hackathonDoorTime: "09:00"
# hackathonEndTime: "2014-10-25T00:00"
# viewOnMap: "View on Google Maps"
# hackathonPlaceCoordinates: "49.840999, 24.031144"
# hackathonMapCenterCoordinates: "49.840696, 24.028754"
# hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
